-- ============================================================================
-- INFRAESTRUCTURA DE NEWSLETTER (ESTRUCTURA FINAL)
-- ============================================================================

-- 1. Eliminar tabla anterior si existe (por seguridad)
DROP TABLE IF EXISTS public.newsletter_suscriptores;

-- 2. Eliminar funciones existentes para evitar conflictos de tipo de retorno (ERROR 42P13)
DROP FUNCTION IF EXISTS public.validar_cupon(TEXT, UUID, DECIMAL);
DROP FUNCTION IF EXISTS public.validar_cupon(TEXT, UUID, NUMERIC);
DROP FUNCTION IF EXISTS public.aplicar_cupon(UUID, UUID, UUID, DECIMAL);
DROP FUNCTION IF EXISTS public.aplicar_cupon(UUID, UUID, UUID, NUMERIC);
DROP FUNCTION IF EXISTS public.generar_codigo_descuento();

-- 3. Crear la tabla cupones_newsletter con las columnas específicas de la imagen
CREATE TABLE IF NOT EXISTS public.cupones_newsletter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    porcentaje_descuento INTEGER DEFAULT 10,
    usado BOOLEAN DEFAULT FALSE,
    orden_id UUID REFERENCES public.ordenes(id) ON DELETE SET NULL,
    fecha_expiracion TIMESTAMPTZ,
    creado_en TIMESTAMPTZ DEFAULT NOW(),
    usado_en TIMESTAMPTZ
);

-- Índice para búsquedas rápidas por código y email
CREATE INDEX IF NOT EXISTS idx_cupones_newsletter_codigo ON public.cupones_newsletter(codigo);
CREATE INDEX IF NOT EXISTS idx_cupones_newsletter_email ON public.cupones_newsletter(email);

-- 3. Función para generar un código de descuento aleatorio (formato NEW-XXXX)
CREATE OR REPLACE FUNCTION public.generar_codigo_descuento()
RETURNS TEXT AS $$
DECLARE
    v_chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    v_code TEXT := 'NEW-';
    i INT;
BEGIN
    FOR i IN 1..8 LOOP
        v_code := v_code || substr(v_chars, floor(random() * length(v_chars) + 1)::INT, 1);
    END LOOP;
    RETURN v_code;
END;
$$ LANGUAGE plpgsql;

-- 4. Actualizar validar_cupon para que busque en cupones_newsletter si no existe en cupones normal
CREATE OR REPLACE FUNCTION public.validar_cupon(
  p_codigo TEXT,
  p_usuario_id UUID,
  p_subtotal DECIMAL
)
RETURNS TABLE(
  cupon_id UUID,
  valido BOOLEAN,
  descuento_calculado DECIMAL,
  descripcion TEXT,
  mensaje TEXT
) AS $$
DECLARE
  v_cupon RECORD;
  v_uso_previo INT;
  v_descuento DECIMAL;
BEGIN
  -- 1. Buscar en cupones normales primero
  SELECT c.id, c.codigo, c.descripcion, c.tipo_descuento, c.valor_descuento, 
         c.cantidad_minima_compra, c.limite_usos, c.usos_totales, 
         c.fecha_inicio, c.fecha_expiracion, c.activo, c.uso_unico_por_usuario
  INTO v_cupon
  FROM public.cupones c
  WHERE UPPER(c.codigo) = UPPER(p_codigo);
  
  -- 2. Si no existe, buscar en cupones_newsletter
  IF v_cupon IS NULL THEN
    SELECT (lpad(id::TEXT, 8, '0') || '-0000-0000-0000-000000000000')::UUID as id, codigo, 'Descuento Newsletter' as descripcion, 
           'porcentaje' as tipo_descuento, porcentaje_descuento as valor_descuento,
           0 as cantidad_minima_compra, 1 as limite_usos, (CASE WHEN usado THEN 1 ELSE 0 END) as usos_totales,
           creado_en as fecha_inicio, fecha_expiracion, NOT usado as activo, TRUE as uso_unico_por_usuario
    INTO v_cupon
    FROM public.cupones_newsletter
    WHERE UPPER(codigo) = UPPER(p_codigo);
  END IF;

  -- Validar existencia
  IF v_cupon IS NULL THEN
    RETURN QUERY SELECT NULL::UUID, false, 0::DECIMAL, ''::TEXT, 'Cupón no encontrado'::TEXT;
    RETURN;
  END IF;
  
  -- Validar que esté activo
  IF NOT v_cupon.activo THEN
    RETURN QUERY SELECT v_cupon.id, false, 0::DECIMAL, v_cupon.descripcion, 'Este cupón ya ha sido usado o no está activo'::TEXT;
    RETURN;
  END IF;
  
  -- Validar fechas
  IF v_cupon.fecha_inicio IS NOT NULL AND NOW() < v_cupon.fecha_inicio THEN
    RETURN QUERY SELECT v_cupon.id, false, 0::DECIMAL, v_cupon.descripcion, 'Este cupón aún no está vigente'::TEXT;
    RETURN;
  END IF;
  
  IF v_cupon.fecha_expiracion IS NOT NULL AND NOW() > v_cupon.fecha_expiracion THEN
    RETURN QUERY SELECT v_cupon.id, false, 0::DECIMAL, v_cupon.descripcion, 'Este cupón ha expirado'::TEXT;
    RETURN;
  END IF;
  
  -- Validar uso previo por usuario
  IF p_usuario_id IS NOT NULL AND v_cupon.uso_unico_por_usuario THEN
    -- Verificar en cupones_uso si es un cupón normal
    SELECT COUNT(*) INTO v_uso_previo
    FROM public.cupones_uso cu
    WHERE cu.cupon_id = v_cupon.id AND cu.usuario_id = p_usuario_id;
    
    IF v_uso_previo > 0 THEN
      RETURN QUERY SELECT v_cupon.id, false, 0::DECIMAL, v_cupon.descripcion, 'Ya has usado este cupón anteriormente'::TEXT;
      RETURN;
    END IF;
  END IF;
  
  -- Validar mínimo de compra
  IF v_cupon.cantidad_minima_compra IS NOT NULL AND p_subtotal < v_cupon.cantidad_minima_compra THEN
    RETURN QUERY SELECT v_cupon.id, false, 0::DECIMAL, v_cupon.descripcion,
      ('Compra mínima requerida: ' || v_cupon.cantidad_minima_compra || '€')::TEXT;
    RETURN;
  END IF;
  
  -- Calcular descuento
  IF v_cupon.tipo_descuento = 'porcentaje' THEN
    v_descuento := ROUND((p_subtotal * v_cupon.valor_descuento / 100), 2);
  ELSE -- cantidad_fija
    v_descuento := LEAST(v_cupon.valor_descuento, p_subtotal);
  END IF;
  
  RETURN QUERY SELECT v_cupon.id, true, v_descuento, v_cupon.descripcion,
    ('Descuento de ' || v_descuento || '€ aplicado')::TEXT;
END;
$$ LANGUAGE plpgsql;

-- 5. Actualizar aplicar_cupon para registrar el uso en la tabla correcta
CREATE OR REPLACE FUNCTION public.aplicar_cupon(
  p_cupon_id UUID,
  p_usuario_id UUID,
  p_orden_id UUID,
  p_descuento DECIMAL
)
RETURNS BOOLEAN AS $$
DECLARE
  v_id_text TEXT;
  v_newsletter_id BIGINT;
BEGIN
  -- Intentar convertir el UUID de vuelta a BIGINT si termina en -0000-0000-0000-000000000000
  v_id_text := p_cupon_id::TEXT;
  
  IF v_id_text LIKE '%-0000-0000-0000-000000000000' THEN
    v_newsletter_id := split_part(v_id_text, '-', 1)::BIGINT;
    
    -- Marcar como usado en cupones_newsletter
    UPDATE public.cupones_newsletter
    SET usado = TRUE,
        orden_id = p_orden_id,
        usado_en = NOW()
    WHERE id = v_newsletter_id;
    
    RETURN TRUE;
  ELSE
    -- Comportamiento normal para cupones estándar
    -- Insertar registro de uso
    INSERT INTO public.cupones_uso (cupon_id, usuario_id, orden_id, descuento_aplicado)
    VALUES (p_cupon_id, p_usuario_id, p_orden_id, p_descuento);
    
    -- Incrementar contador global
    UPDATE public.cupones
    SET usos_totales = COALESCE(usos_totales, 0) + 1,
        actualizado_en = NOW()
    WHERE id = p_cupon_id;
    
    RETURN TRUE;
  END IF;
END;
$$ LANGUAGE plpgsql;
